export type { NewsDesc } from './news-desc';
export type { NewsDescDto } from './news-desc';
export type { Material } from './material';
export type { SortOption } from './sort-option';
export type { CreateWorkDto, TypedGetWorkDto as GetWorkDto } from './work';
export type { CreateSaleDto, GetSaleDto } from './sale';
export type { Base } from './base';
export type { RequestResult } from './request-result';
export type { UserPassPair } from './userpasspair';
export type { CommonGetWorkDto } from './common_work';
export type { GetBaseWork } from './base_work';
export type { UpdateWorkResponse,  UpdateWorkRequest} from './work';
export type { UpdateSaleResponse, UpdateSaleRequest } from './sale';
