export type { NewsItemType } from './news-item-type';
export type { NewsDesc } from './news-desc';
export type { NewsDescDto } from './news-desc';
export type { Material } from './material';
export type { SortOption } from './sort-option';
export type { CreateWorkDto } from './work';
export type { AddSaleDto, Sale } from './sale';
export type { Base } from './base';
export type { RequestResult } from './request-result';
export type { UserPassPair } from './userpasspair';
