# Image Storage Settings
app:
  name: "Vera Art"
  port: 8000

# CORS configuration
cors:
  allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"
  debug: false

# Directory where images will be stored
directories:
  abs_works_dir: "/Users/raiyin/projects/mac/client"
  rel_works_dir: "/content/works/"
  abs_sales_dir: "/Users/raiyin/projects/mac/client"
  rel_sales_dir: "/content/sales/"
  news_dir_save: "/Users/raiyin/projects/mac/client"
  news_db_dir_prefix: "/content/news/"
